version: "3.5"

services:
  server:
    build: 
      context: .
      dockerfile: Dockerfile.web
    image: node-dev
    container_name: node_server
    restart: on-failure
    env_file:
     - docker-environment.dev
    command:
     - ./docker-entrypoint-dev-app.sh
    volumes:
      - .:/home/node_user/
      - /home/node_user/node_modules
    ports:
      - "3000:3000"
    extra_hosts:
      - "local.test-app.com:172.17.0.1"
    networks:
     - tapp_dev

  db:
    image: postgres:11-alpine
    container_name: postgres
    environment:
     - POSTGRES_DB=tapp_dev
    ports:
     - "5432:5432"
    networks:
     - tapp_dev
    volumes:
     - db_data:/var/lib/postgresql/data


networks:
  tapp_dev:
      name: tapp_dev

volumes:
  db_data:
    name: tapp-db-data