FROM node:10-alpine

RUN adduser --disabled-password --gecos '' node_user
WORKDIR /home/node_user

COPY package*.json ./

RUN apk add --no-cache --virtual .gyp python make g++ \
    && npm install \
    && npm install -g knex \
    && apk del .gyp

COPY . .

RUN chmod +x docker-entrypoint-dev-app.sh \
    && chown -R node_user:node_user ./

USER node_user
CMD npm run dev
